webhook isn't working. trying gcloud command

diff --git a/cardano-node-iohk/cloudbuild.yaml b/cardano-node-iohk/cloudbuild.yaml
--- a/cardano-node-iohk/cloudbuild.yaml
+++ b/cardano-node-iohk/cloudbuild.yaml
@@ -18,22 +18,61 @@ steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['image', 'push', 'floydcraft/cardano-node-iohk']
 
-  - name: 'gcr.io/cloud-builders/curl'
+  - name: 'gcr.io/cloud-builders/gcloud'
     entrypoint: 'bash'
-    args: ['-c', 'curl https://cloudbuild.googleapis.com/v1/projects/cardano-etl/triggers/cardano-node-iohk-slim-webhook:webhook?secret=$$CARDANO_ETL_WEBHOOK&key=$$CARDANO_ETL_API_KEY']
-    secretEnv: [ 'CARDANO_ETL_API_KEY', 'CARDANO_ETL_WEBHOOK' ]
+    args:
+      - '-c'
+      - |
+      - dir="cardano-node-iohk-slim"
+        echo "Building $dir ... "
+        logfile="$dir.log"
+        failfile="$dir.fail"
+        gcloud builds submit $dir --config=$dir/cloudbuild.xml > ${logfile} 2>&1
+        if [[ $? -ne 0 ]]; then
+          echo "$dir failed" | tee -a ${failfile}
+          cat ${logfile}
+        fi
+        # Check if there is any failure.
+        if [[ -s ${failfile} ]]; then
+          echo
+          echo "build failed:"
+          cat ${logfile}
+          echo "Exiting."
+          exit 1
+        fi
+        echo "Build succeeded."
 
-timeout: 5000s
+  - name: 'gcr.io/cloud-builders/gcloud'
+      entrypoint: 'bash'
+      args:
+        - '-c'
+        - |
+        - dir="cardano-node-slim"
+          echo "Building $dir ... "
+          logfile="$dir.log"
+          failfile="$dir.fail"
+          gcloud builds submit $dir --config=$dir/cloudbuild.xml > ${logfile} 2>&1
+          if [[ $? -ne 0 ]]; then
+          echo "$dir failed" | tee -a ${failfile}
+          cat ${logfile}
+          fi
+          # Check if there is any failure.
+          if [[ -s ${failfile} ]]; then
+          echo
+          echo "build failed:"
+          cat ${logfile}
+          echo "Exiting."
+          exit 1
+          fi
+          echo "Build succeeded."
+
+timeout: 8000s
 options:
   machineType: 'N1_HIGHCPU_8'
 availableSecrets:
   secretManager:
     - versionName: projects/cardano-etl/secrets/docker-chbfiv/versions/1
       env: 'DOCKER_API_KEY'
-    - versionName: projects/cardano-etl/secrets/cardano-etl-api-key/versions/1
-      env: 'CARDANO_ETL_API_KEY'
-    - versionName: projects/cardano-etl/secrets/cardano-etl-webhook/versions/1
-      env: 'CARDANO_ETL_WEBHOOK'
 
 
 
